Feature
menyagah/ruby_bubblesort pull request #1
Opened 2020-06-14 17:14 UTC by menyagah

#In this section we:
- Created a bubble sort algorithm that sorts items in an array in ascending order. 
- Created another method bubble_sort_by that sorts the array in both the ascending and descending order using the yield and block method.

2020-06-14 21:18 UTC, MarioDena requested changes
## Changes required

See my comment! 😄

2020-06-14 21:18 UTC, MarioDena commented on bubblesort.rb
> +end
Hello Great job on your project everything is working great except for 1 small error checking! 👍 

## Requested Changes 

- [ ] Your bubble sort by method should return an error if no block is given.

That's all, so a small error handling changes and you are good to go!

Cheers!

2020-06-15 11:47 UTC, lekegitrepo commented
#### Hi @menyagah and @mugberto :clap: :clap:
#### Good job for implementing the required changes :muscle:

### _Reviewed by Temitayo Adeleke._

2020-06-15 11:48 UTC, lekegitrepo approved these changes
#### Status: Approved

2020-06-15 12:25 UTC, merged